trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --user poetry
      echo "##vso[task.prependpath]$(python -m site --user-base)/bin"
    displayName: 'Install Poetry via pip'

  - script: poetry install
    displayName: 'Install dependencies'

  - script: poetry run pytest
    displayName: 'Run tests'
